---

services:
  postgres_node1:
    image: postgres:14
    container_name: postgres_node1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: mydatabase
  # Enable logical replication
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - pgdata_node1:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Expose port for replication and access
    restart: always

  postgres_node2:
    image: postgres:14
    container_name: postgres_node2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata_node2:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Change port to avoid conflicts
    restart: always

  postgres_node3:
    image: postgres:14
    container_name: postgres_node3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata_node3:/var/lib/postgresql/data
    ports:
      - "5434:5432"  # Change port to avoid conflicts
    restart: always

volumes:
  pgdata_node1:
  pgdata_node2:
  pgdata_node3: 
